### ISSUE TITLE
Dark Mode 

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/gatsby-oi-wiki#102]
或许可以参考：

https://stackoverflow.com/questions/52379118/want-to-change-pick-primary-color-dynamically-in-material-ui-theme
https://material-ui.com/customization/globals/

**Comment by Enter-tainer** [comment]
目前，theme 还有如下问题：

- ![image](https://user-images.githubusercontent.com/25521218/81131801-f490c100-8f7e-11ea-97b4-c5f0537a9f68.png) 行内代码颜色难以辨认

- ![image](https://user-images.githubusercontent.com/25521218/81131816-03777380-8f7f-11ea-9350-f3e63361c352.png) details 在暗色模式下，蓝色背景过亮

- footer 颜色是亮色的

**Comment by diauweb** [comment]
#150

**Comment by diauweb** [comment]
[ ] tab 在hover时是黑的

**Comment by Enter-tainer** [comment]
将 Change Primary Color 搬运到 #150 处理
