### ISSUE TITLE
使用小屏幕版本搜索框后扩大页面搜索框宽度不正常

### ISSUE THREAD

**Issue by diauweb** [OI-wiki/gatsby-oi-wiki#118]

**Comment by Ir1d** [comment]
Ir1d XD+, [21.04.20 21:07]
我想知道具体是啥样（

Ir1d XD+, [21.04.20 21:07]
没有 backdrop 可能是因为卡了

Ir1d XD+, [21.04.20 21:07]
现在的实现是只存了 key，结果没存

Ir1d XD+, [21.04.20 21:07]
所以切换尺寸会重新 fetch 一遍

或许可以把搜索结果也存到 state 里面（

**Comment by diauweb** [comment]
有backdrop 是我描述错误了 现在这个问题变成搜索框宽度不正常了（（
