### ISSUE TITLE
mathjax SSR

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/gatsby-oi-wiki#139]
Margatroid, [04.05.20 20:33]
现在点击链接之后，应该会去请求数据，等数据到了之后再显示

Ir1d XD+, [04.05.20 20:40]
[In reply to Margatroid]
对我感觉是这样的，然后因为我这里网络比较卡貌似这个请求会拖一阵子 😂 就是看起来点击了链接但是没有跳转

Xiaodai Dai, [04.05.20 20:41]
+1

Ir1d XD+, [04.05.20 20:41]
感觉可能是  gatsby 的 feature

---

Margatroid, [04.05.20 20:42]
那感觉这个问题可以通过加进度条—或者说更广义的，通过与 react 交互来实现？

Margatroid, [04.05.20 20:42]
比如点了之后，立即把正文的内容变成骨架屏

**Comment by Enter-tainer** [comment]
解决方案之一，是调整 service worker 的缓存策略。比如将文章相关的 json 的缓存策略改为 staleWhileRevalidate。

**Comment by Enter-tainer** [comment]
mgt, [09.05.20 21:46]
话说如果把 json 的缓存策略调成 staleWhileRevalidate 可以接受吗

mgt, [09.05.20 21:47]
就是，先从 cache（可能失效了，也可能没失效） 里面拿出来东西给你看，与此同时，发一个请求去请求一下新的 json，看看有没有更新

mgt, [09.05.20 21:48]
这样做的优点是速度飞快，缺点是，页面更新后，第一次访问到的是旧的东西

mgt, [09.05.20 21:48]
欸，我们没有缓存 html，那么这似乎意味着，只要刷新一下，就能获得最新的页面内容

demo: https://stale-while-revalidate-oi-wiki.surge.sh

**Comment by Ir1d** [comment]
possible related https://github.com/gatsbyjs/gatsby/issues/21193

**Comment by Enter-tainer** [comment]
与 #183 为同一个问题，原因在于目前的 sidebar 和 nav 太慢了。

mathjax 的速度似乎也影响了加载，可以通过换成 ssr 解决

**Comment by Ir1d** [comment]
小结一下今天下午的发现：

- 转纯静态的插件 https://github.com/wardpeet/gatsby-plugin-static-site
- 换 preact https://henrique.codes/speed-up-gatsby-site/

**Comment by Enter-tainer** [comment]
目前的进度：

- 问题与网络关系不大，主要是因为 sidebar 和 nav 性能太差，重渲染时占用时间过长
- mathjax 也导致了页面切换时的性能下降，可以通过服务端渲染公式解决，需要等待上游
- sidebar 的性能原因可能是因为组件递归过深，具体原因还需要继续排查

**Comment by Enter-tainer** [comment]
目前为了防止 mathjax 阻塞渲染，使用了 requestIdelCallback，会出现导致公式渲染时发生页面位移。

上游的公式 SSR 完工后可以切换成 SSR 避免这个问题

**Comment by Enter-tainer** [comment]
记录一下目前的进度：

remark-mathjax 似乎和 mdx 不和，主要发现的错误是 svg 标签中的属性名字出现了大小写错误，如 `xmlns:xlink="http://www.w3.org/1999/xlink"` 变成了 `xmlnsXLink`。

目前怀疑是上游问题，正在高强度 review 上游代码 🌚

**Comment by Enter-tainer** [comment]
目前成功排查出 chtml 模式下的问题：

html 标签应该用 class 表示 css 类，而渲染产物使用了 classname，怀疑是上游的序列化问题

**Comment by Enter-tainer** [comment]
继续记录进度，怀疑是 https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/ 的问题，开始 review 代码

**Comment by Enter-tainer** [comment]
目前的发现是，在 doc.js 里 log 了 mdx.body，发现 mathjax 和其它标签使用 className 的方式完全一样，但是渲染出来的结果不同

**Comment by Enter-tainer** [comment]
继续记录进度，review 了 `@mdx/react` 和 `gatsby-plugin-mdx` 的代码之后，得出结论是，序列化的过程，是由 `doc.js` 里的 `mdx.body` 实现了，接下来可以重点 review 这一部分

**Comment by Enter-tainer** [comment]
结论是这样的，mdx.body 内部的代码最终调用 React.creatElement。而该 API 对于自定义的标签行为诡异，不会实现 className -> class 的转换，最终导致了 bug

workaround 是用正则手动替换所有 Mathjax 相关的 className 为 class

**Comment by Enter-tainer** [comment]
https://github.com/facebook/react/issues/19105

**Comment by Enter-tainer** [comment]
#260 完成之后，可以切换到 preact
