### ISSUE TITLE
添加 setting 页

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/gatsby-oi-wiki#150]
有一些东西不太适合我们替用户做决定，可以做成设置页，让用户自己选择：

- 主题色和强调色
- 暗色模式是否启用/定时启用/根据偏好启用
- 暗色模式下图片亮度
- 是否启用滚动动画

待补充...

**Comment by Ir1d** [comment]
settings 是不是一个 dialog 怼脸上也行 :thinking:

**Comment by Enter-tainer** [comment]
> settings 是不是一个 dialog 怼脸上也行 🤔

理论上是这样，但是可能做成 page 更好写一点（
