### ISSUE TITLE
在点目录的时候，会先跳出一个 footer 再往下滑动

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/gatsby-oi-wiki#182]
Xiaodai Dai, [09.05.20 17:25]
先出footer的问题需要精准刀法

Xiaodai Dai, [09.05.20 17:25]
把footer也想办法用选择器选中了

Xiaodai Dai, [09.05.20 17:25]
可能需要外面再套一层元素

**Comment by sshwy** [comment]
这个bug咋复现呢

**Comment by sshwy** [comment]
有一个思路
先把content和footer用一个div包起来，然后把toc用protal渲染到外面去（防止toc跟着滚动）
然后选择器选中这个div
