### ISSUE TITLE
切换主题时会产生卡顿现象

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/gatsby-oi-wiki#183]
注意到 mui 的文档里面切换速度很快，或许可以学习一下做法

**Comment by Ir1d** [comment]
感觉是在这里 https://github.com/mui-org/material-ui/blob/master/docs/src/modules/components/ThemeContext.js#L186 ，但是还没看出来是为啥那么快

**Comment by Enter-tainer** [comment]
moved to #139
