### ISSUE TITLE
TOC 覆盖在footer之上

### ISSUE THREAD

**Issue by diauweb** [OI-wiki/gatsby-oi-wiki#185]
**Expected behavior:**
为 toc 在页面下方可以留出足够空白

**Comment by Enter-tainer** [comment]
问一下怎么复现

我把窗口拉成非常奇怪的形状之后才复现成功

**Comment by diauweb** [comment]
![image](https://user-images.githubusercontent.com/13145192/81500625-f1426000-9305-11ea-92c4-42f8e4a84b22.png)

**Comment by Enter-tainer** [comment]
fixed
