### ISSUE TITLE
.md 内链不工作

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/gatsby-oi-wiki#188]
曾经某一时刻好像是工作的，不太清楚是不是插件问题（那个啥 copy file 的）

example: https://ng.oi-wiki.org/test/ 里面那个指向 index.md 的

**Comment by Enter-tainer** [comment]
https://ng.oi-wiki.org/math/poly/newton/

看起来这里的内链是 work 的。

或许是 xxx.md 本身的期望行为就是这样的？

**Comment by Ir1d** [comment]
https://github.com/OI-wiki/gatsby-oi-wiki/blame/master/docs/math/poly/newton.md#L71

是的，应该是只有 .md 形式的不 work，但是我们会有大量 .md 形式的..

**Comment by Ir1d** [comment]
https://github.com/OI-wiki/gatsby-oi-wiki/blob/master/src/components/Link.js#L22 这里似乎进行了处理.. 但是目前似乎还是不 work

**Comment by Enter-tainer** [comment]
https://ng.oi-wiki.org/math/poly/newton/

内链炸了 #194

**Comment by Enter-tainer** [comment]
fixed
