### ISSUE TITLE
文章锚点出现问题

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/gatsby-oi-wiki#196]
- hover 时的图标不工作
- 点击 TOC 时，目标锚点被header覆盖

**Comment by CBW2007** [comment]
@Enter-tainer 是不是link的样式覆盖进去了？

**Comment by Enter-tainer** [comment]
目前通过删除 link 样式暂时解决。但如果无法妥善解决此问题，可能会影响 #203
