### ISSUE TITLE
details 中的行内代码标签错误

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/gatsby-oi-wiki#202]
details 中的行内代码标签变成了 `<inlinecode>`,而不是`<code>`，导致 react 在 console 报错。
![image](https://user-images.githubusercontent.com/25521218/82719646-16a87400-9cdf-11ea-9e46-69a72f5e6575.png)

![image](https://user-images.githubusercontent.com/25521218/82719650-1c9e5500-9cdf-11ea-8f21-61f39afe6053.png)

目前无法确定原因

**Comment by Ir1d** [comment]
盲猜是 remark 侧的问题，等我看看

**Comment by Enter-tainer** [comment]
检查了 remark-details，发现在本地运行时，序列化得到的行内代码具有正常的标签名。

可能问题出在了我们这里的渲染方式上

**Comment by Enter-tainer** [comment]
https://github.com/mdx-js/mdx/blob/master/packages/mdx/mdx-ast-to-mdx-hast.js#L10

在 review 上游代码的时候发现了与 inlineCode 相关的内容，需要进一步研究

**Comment by Enter-tainer** [comment]
在 26f305fbbcea66a11e1b0edc811bf5de36a21eb3 中，通过组件替换作为 workaround。
