### ISSUE TITLE
暗色模式在首次访问时产生闪动

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/gatsby-oi-wiki#291]
由于 js 会在 html 之后加载，因此写在 js 中的暗色模式的相关逻辑往往会在网页元素显示出来之后才能得到加载。而在进行服务端渲染时，默认的主题是亮色主题。因此，如果用户设置了暗色模式，在首次访问的时候，会先看到亮色的页面，然后在 js 加载完毕后才会变成暗色。

解决这个问题，需要在页面的头部加载一个较为轻量的 js 来处理暗色模式的相关逻辑。

**Comment by diauweb** [comment]
#205
