### ISSUE TITLE
代码高亮的 Light/Dark 模式自适应问题

### ISSUE THREAD

**Issue by CoelacanthusHex** [OI-wiki/gatsby-oi-wiki#628]
![图片](https://user-images.githubusercontent.com/43064781/107040036-a6546b00-67f9-11eb-9bd4-d3976a166e6f.png)

![图片](https://user-images.githubusercontent.com/43064781/107040080-b3715a00-67f9-11eb-8bbc-082c534964de.png)

https://fatihkalifa.com/typescript-twoslash

_Originally posted by @Enter-tainer, @sshwy and @CoelacanthusHex in Telegram Group_

**Comment by Enter-tainer** [comment]
https://github.com/shikijs/shiki/issues/33

https://github.com/microsoft/TypeScript-Website/pull/1536

上游直接整了个CSS滤镜，看起来还行

**Comment by CoelacanthusHex** [comment]
> [shikijs/shiki#33](https://github.com/shikijs/shiki/issues/33)
> 
> [microsoft/TypeScript-Website#1536](https://github.com/microsoft/TypeScript-Website/pull/1536)
> 
> 上游直接整了个CSS滤镜，看起来还行

看起来还可以

**Comment by Enter-tainer** [comment]
done in #708

**Comment by Enter-tainer** [comment]
https://github.com/shikijs/shiki/issues/33#issuecomment-778834117 上游的另一解
