### ISSUE TITLE
添加sitemap

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/gatsby-oi-wiki#668]

**Comment by CBW2007** [comment]
经测试，原来的sitemap出问题的原因是它使用了已被弃用的`url.resolve`方法，导致在某些情况下会出问题。现在正在尝试修改

**Comment by CBW2007** [comment]
> 经排查，原来的sitemap出问题的原因是它使用了已被弃用的`url.resolve`方法，导致在某些情况下会出问题。现在正在尝试修改

似乎只是原因之一。这样改的话所有页面都会查到sitemap-pages.xml，sitemap-documents.xml里面都是undefined..

**Comment by diauweb** [comment]
upstream https://github.com/TryGhost/gatsby-plugin-advanced-sitemap/pull/136
