### ISSUE TITLE
部分代码高亮颜色不对劲

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/gatsby-oi-wiki#679]
https://next.oi-wiki.org/contest/problemsetting/#%E8%BE%93%E5%85%A5%E8%BE%93%E5%87%BA%E6%A0%BC%E5%BC%8F

**Comment by sshwy** [comment]
@Enter-tainer

**Comment by Enter-tainer** [comment]
![image](https://user-images.githubusercontent.com/25521218/107775149-e5933680-6d7a-11eb-8ad1-96f23b291b14.png)

看起来是因为shiki对latex的支持的问题，准备尝试更新一下上游的主题
