### ISSUE TITLE
author field 的改进 proposal

### ISSUE THREAD

**Issue by ksyx** [OI-wiki/gatsby-oi-wiki#681]
目前贡献者有点刺眼 表现在 `@` 太多了以及巨大量下划线里混着少量的非下划线 以及（不是这么重要的）贡献者放在了页面顶部

proposal 是把显示方式换成*不明显*的按钮，即，
- 用背景色与页面颜色相差不大的圆角矩形包着 contributor name
- 去除 `@` 和下划线
- hover 时颜色变深

**Comment by diauweb** [comment]
@ksyx +可以在小屏幕下默认收起贡献者

**Comment by ksyx** [comment]
> +可以在小屏幕下默认收起贡献者

+ 设置里隐藏？（*可能降低贡献积极性

**Comment by sshwy** [comment]
我个人蛮喜欢 @ 符，也不觉得下划线有啥问题
相反我觉得一万个圆角矩形排一起有点annoying
按扭本应该是action，而不是link :thinking: 
（仅代表个人喜好

**Comment by ksyx** [comment]
> 我个人蛮喜欢 @ 符，也不觉得下划线有啥问题
> 相反我觉得一万个圆角矩形排一起有点annoying
> 按扭本应该是action，而不是link :thinking: 
> （仅代表个人喜好

所以不要让按钮特征这么明显🤔

**Comment by sshwy** [comment]
onhover的效果可以来一个

**Comment by Enter-tainer** [comment]
- [x] 去除下划线
- [] 小屏默认折叠

**Comment by ouuan** [comment]
我希望能 link 到类似于 https://github.com/OI-wiki/OI-wiki/commits/master/docs/graph/concept.md?author=ouuan 的页面

**Comment by ouuan** [comment]
样式的话我觉得可以去掉下划线保留 @

**Comment by CBW2007** [comment]
![icon](https://user-images.githubusercontent.com/42204218/107750439-fe89f080-6d56-11eb-8fbc-6df1ee0056d5.jpg)

曾经其实是提到过这种样式的，然后被否掉了（

**Comment by sshwy** [comment]
@ouuan 已经实现了（不过好像还没同步到next，可以先去ng看看

**Comment by Enter-tainer** [comment]
大家觉得把 贡献者 移到页面底部的位置可以吗？

**Comment by ksyx** [comment]
> 大家觉得把 贡献者 移到页面底部的位置可以吗？

好诶好诶

**Comment by Enter-tainer** [comment]
目前已经移到了页面底端，closed
