### ISSUE TITLE
引用功能出现问题

### ISSUE THREAD

**Issue by CBW2007** [OI-wiki/gatsby-oi-wiki#703]
引用时链接的位置会出现错误（类似#44）。另外，在目录中带有引用的标题也无法定位（锚点名称不吻合，直接回到了开头）。

可测试地址：<https://next.oi-wiki.org/tools/wsl/>

**Comment by sshwy** [comment]
有两个解决方案

1. 整一个remark 插件，如果没有现成的就自己造
2. 在钦定：有id的sup是ref，有id的li是footnote的情况下，可以在gatsby-oi-wiki里实现
