### ISSUE TITLE
暗色模式下，代码块不清楚

### ISSUE THREAD

**Issue by alphagocc** [OI-wiki/gatsby-oi-wiki#754]
![image](https://user-images.githubusercontent.com/28982331/111056592-2df95d80-84bb-11eb-950f-84a9d26a0d50.png)
![image](https://user-images.githubusercontent.com/28982331/111056596-36519880-84bb-11eb-9692-9d4278947410.png)
屏幕为为1920*1080,使用windows下的chrome

**Comment by Enter-tainer** [comment]
相关上游issue：https://github.com/shikijs/shiki/issues/33

**Comment by Enter-tainer** [comment]
![image](https://user-images.githubusercontent.com/25521218/118407065-857d9a80-b6b1-11eb-9596-3988e6be4d80.png)

mgt, [17.05.21 01:43]
是那种 纯文本格式的代码块

mgt, [17.05.21 01:44]
或者是没有识别出来是什么语言的代码块

在暗色模式下, 会变成黑色
