### ISSUE TITLE
需求：添加伪代码语法

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/gatsby-oi-wiki#82]
目前通过 mathjax 的实现太复杂了，维护起来压力太大

期望行为是来个纯文本的

```
```pseudo
```
```

可能需要类似 details 那样搞，来一组 remark 和 rehype 侧的工具来支持

**Comment by diauweb** [comment]
还是先稍微更新一下动态，不然好像这个issue就要被忘了（
备选方案：
- LaTeX favour [pseudocodejs](//github.com/SaswatPadhi/pseudocode.js)
- LISP favour (prototype) [remark-pseudocode](//github.com/diauweb/remark-pseudocode)
