### ISSUE TITLE
折叠框不能包住全部内容

### ISSUE THREAD

**Issue by diauweb** [OI-wiki/gatsby-oi-wiki#83]
https://oi-wiki.org/math/poly/fft/
![image](https://user-images.githubusercontent.com/13145192/79068029-5b131e00-7cf6-11ea-8bbc-0e38b5a3609f.png)

**Comment by Enter-tainer** [comment]
这个应该是 remark-details 的实现问题

**Comment by Ir1d** [comment]
确实，那个空格干掉之后我不太会整，，我建议先留着 4 个 prefix 空格

主站的源文件：
![image](https://user-images.githubusercontent.com/10709657/79068882-cb24a280-7cfc-11ea-9dbe-1389ca6fdf82.png)

这边：
![image](https://user-images.githubusercontent.com/10709657/79068909-e7c0da80-7cfc-11ea-80e2-bbc5a75a1ecf.png)

**Comment by sshwy** [comment]
这个是不是不太能修啊，要不close了？

**Comment by Ir1d** [comment]
还是有希望的，因为每个环节都可控 :joy: 
只是一直没空 dive deep into the implementation :new_moon_with_face:

**Comment by Ir1d** [comment]
我提一下修的思路，如果谁这会有空可以先瞅瞅 :eyes: 
大概就是 https://facelessuser.github.io/pymdown-extensions/extensions/details/ 这个 python version 很 work，但我抄过来的 node version https://github.com/OI-wiki/remark-details 需要前缀空格，想修的话需要对比下实现哪里出了问题 :joy:

**Comment by sshwy** [comment]
其实我一直觉得前缀空格的details语法对任何编辑器都不太友好
我寻思要不直接搞一个新语法
就像 ``` 代码块这种（

**Comment by sshwy** [comment]
修好了（
