### ISSUE TITLE
添加前后页面链接

### ISSUE THREAD

**Issue by Tim-Paik** [OI-wiki/gatsby-oi-wiki#833]
如题，希望有类似主站那样的在页脚有上一页、下一页的链接
移动设备每次切换下一页都需要打开侧边栏 (sidebar) 
主站可以直接访问下一页

**Comment by Enter-tainer** [comment]
根据群里的讨论

> CBW2007, [15.05.21 09:25]
> 没有啥实际用途吧
> 
> CBW2007, [15.05.21 09:26]
> wiki类的文章貌似不像博客/教程一样有先后顺序吧🌚
> 
> Mocha Matcha, [15.05.21 12:45]
> 可以考虑一下下面放个相关文章啥的
> 
> Mocha Matcha, [15.05.21 12:45]
> 上一个下一个意义不大

暂时先 close，如果未来有需求再来实现
