### ISSUE TITLE
小屏幕上更新历史显示效果不佳

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/gatsby-oi-wiki#915]
![image](https://user-images.githubusercontent.com/25521218/126058808-5ed213a0-17f6-4e01-9fd9-a8cb5b4c4e60.png)

https://next.oi-wiki.org/contest/resources/changelog

**Comment by SkyeYoung** [comment]
我像 GitHub 的 commits log 一样，在小屏幕上把时间放到这条的轴线右边可以吗？

**Comment by Enter-tainer** [comment]
@SkyeYoung 可以可以
